name: nexkartt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  provider: ^6.0.5
  uuid: ^4.0.0
  image_picker: ^0.8.7+4
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Ink
      fonts:
        - asset: assets/fonts/Ink.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
          weight: 400
    - family: L-Bold
      fonts: 
        - asset: assets/fonts/L-Bold.ttf
          weight: 700
    - family: LeagueSpartan-Regular
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
          weight: 400
    - family: MAGNETOB
      fonts:
        - asset: assets/fonts/MAGNETOB.TTF  # Fixed space
          weight: 700